"""Services package - extracted from main.py"""
from .market_data import (
    get_live_price,
    get_cached_quote,
    get_cached_candles,
    update_live_price_cache,
    get_cache_stats,
)
from .circuit_breaker import (
    check_circuit_breaker,
    trigger_circuit_breaker,
    reset_circuit_breaker,
    get_circuit_breaker_status,
)
from .signal_generator import (
    calculate_signal_score,
    get_signal_direction,
    calculate_confidence,
    calculate_position_size,
    SignalDirection,
    Component,
)
from .market_hours import (
    is_market_open,
    get_market_hours,
)
from .state import (
    get_account,
    set_account,
    get_open_positions,
    set_open_positions,
    get_closed_positions,
    set_closed_positions,
    get_signals_cache as _get_signals_cache,
    set_signals_cache as _set_signals_cache,
    get_signal_history_cache,
    set_signal_history_cache,
    get_live_price_cache,
    update_live_price_cache as update_price_cache,
    get_auto_trade_enabled,
    set_auto_trade_enabled,
    get_auto_trade_interval,
    set_auto_trade_interval,
    get_instruments,
    set_instruments,
    get_symbol_strategy,
    set_symbol_strategy,
    get_all_strategy_selections,
    get_timing_stats,
    reset_timing_stats,
)

__all__ = [
    "get_live_price",
    "get_cached_quote", 
    "get_cached_candles",
    "update_live_price_cache",
    "get_cache_stats",
    "check_circuit_breaker",
    "trigger_circuit_breaker",
    "reset_circuit_breaker",
    "get_circuit_breaker_status",
    "calculate_signal_score",
    "get_signal_direction", 
    "calculate_confidence",
    "calculate_position_size",
    "SignalDirection",
    "Component",
    "is_market_open",
    "get_market_hours",
    # state
    "get_account",
    "set_account",
    "get_open_positions",
    "set_open_positions",
    "get_closed_positions",
    "set_closed_positions",
    "get_signals_cache",
    "set_signals_cache",
    "get_signal_history_cache",
    "set_signal_history_cache",
    "get_live_price_cache",
    "get_auto_trade_enabled",
    "set_auto_trade_enabled",
    "get_auto_trade_interval",
    "set_auto_trade_interval",
    "get_instruments",
    "set_instruments",
]
